# Generated by Django 2.0.2 on 2018-03-06 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('Date', models.DateTimeField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Emp', models.IntegerField(default=0)),
                ('Role', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Loc', models.IntegerField(default=0)),
                ('Address', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Coordinates', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Prod', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=200)),
                ('Material', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('Date', models.DateTimeField(verbose_name='')),
                ('ID_Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Employees')),
                ('ID_Loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Locations')),
                ('ID_Prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('ID_Loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Locations')),
                ('ID_Prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Products')),
            ],
        ),
        migrations.AddField(
            model_name='distribution',
            name='ID_Loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Locations'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='ID_Prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Products'),
        ),
    ]
