# Generated by Django 2.0.2 on 2018-03-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20180326_2002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Restock',
        ),
    ]
