# Generated by Django 2.0.2 on 2018-03-16 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20180316_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='ID_Loc',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ID_Prod',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
