# Generated by Django 2.0.2 on 2018-03-16 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20180316_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('ID_Loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Locations')),
                ('ID_Prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Products')),
            ],
        ),
    ]
