# Generated by Django 2.0.2 on 2018-03-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20180326_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='Date',
            field=models.DateField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='predictedrequisition',
            name='Date',
            field=models.DateField(primary_key=True, serialize=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='Date',
            field=models.DateField(primary_key=True, serialize=False, verbose_name=''),
        ),
    ]
