# Generated by Django 2.0.2 on 2018-03-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20180328_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Date',
            field=models.DateField(verbose_name=''),
        ),
    ]
