# Generated by Django 2.0.2 on 2018-04-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20180411_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Role',
            field=models.IntegerField(default=''),
        ),
    ]
