# Generated by Django 2.0.2 on 2018-04-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20180411_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Material2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='Material3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='Material4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='Material5',
            field=models.FloatField(default=0),
        ),
    ]
